# Generated by Django 4.1.13 on 2024-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("author", models.CharField(max_length=40)),
                ("price", models.IntegerField()),
                ("discount", models.FloatField(default=0)),
                ("duration", models.DurationField()),
            ],
        ),
    ]
